/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiManifestDotwebmanifestRouteImport } from './routes/api/manifest[.]webmanifest'
import { Route as AuthShopFloorRouteImport } from './routes/_auth/shop-floor'
import { Route as AuthPodesavanjaRouteImport } from './routes/_auth/podesavanja'
import { Route as AuthMonitoringRouteImport } from './routes/_auth/monitoring'
import { Route as AuthIstorijaRouteImport } from './routes/_auth/istorija'
import { Route as AuthPodesavanjaIndexRouteImport } from './routes/_auth/podesavanja.index'
import { Route as ApiPublicVersionRouteImport } from './routes/api/public/version'
import { Route as AuthPodesavanjaRoleRouteImport } from './routes/_auth/podesavanja.role'
import { Route as AuthPodesavanjaPwaRouteImport } from './routes/_auth/podesavanja.pwa'
import { Route as AuthPodesavanjaKorisniciRouteImport } from './routes/_auth/podesavanja.korisnici'
import { Route as AuthPodesavanjaAirtableRouteImport } from './routes/_auth/podesavanja.airtable'
import { Route as ApiPublicAirtableWebhookMonitoringRouteImport } from './routes/api/public/airtable-webhook/monitoring'
import { Route as AuthPodesavanjaAirtableMapiranjeRouteImport } from './routes/_auth/podesavanja.airtable.mapiranje'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiManifestDotwebmanifestRoute =
  ApiManifestDotwebmanifestRouteImport.update({
    id: '/api/manifest.webmanifest',
    path: '/api/manifest.webmanifest',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthShopFloorRoute = AuthShopFloorRouteImport.update({
  id: '/shop-floor',
  path: '/shop-floor',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPodesavanjaRoute = AuthPodesavanjaRouteImport.update({
  id: '/podesavanja',
  path: '/podesavanja',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMonitoringRoute = AuthMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AuthRoute,
} as any)
const AuthIstorijaRoute = AuthIstorijaRouteImport.update({
  id: '/istorija',
  path: '/istorija',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPodesavanjaIndexRoute = AuthPodesavanjaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthPodesavanjaRoute,
} as any)
const ApiPublicVersionRoute = ApiPublicVersionRouteImport.update({
  id: '/api/public/version',
  path: '/api/public/version',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPodesavanjaRoleRoute = AuthPodesavanjaRoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => AuthPodesavanjaRoute,
} as any)
const AuthPodesavanjaPwaRoute = AuthPodesavanjaPwaRouteImport.update({
  id: '/pwa',
  path: '/pwa',
  getParentRoute: () => AuthPodesavanjaRoute,
} as any)
const AuthPodesavanjaKorisniciRoute =
  AuthPodesavanjaKorisniciRouteImport.update({
    id: '/korisnici',
    path: '/korisnici',
    getParentRoute: () => AuthPodesavanjaRoute,
  } as any)
const AuthPodesavanjaAirtableRoute = AuthPodesavanjaAirtableRouteImport.update({
  id: '/airtable',
  path: '/airtable',
  getParentRoute: () => AuthPodesavanjaRoute,
} as any)
const ApiPublicAirtableWebhookMonitoringRoute =
  ApiPublicAirtableWebhookMonitoringRouteImport.update({
    id: '/api/public/airtable-webhook/monitoring',
    path: '/api/public/airtable-webhook/monitoring',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthPodesavanjaAirtableMapiranjeRoute =
  AuthPodesavanjaAirtableMapiranjeRouteImport.update({
    id: '/mapiranje',
    path: '/mapiranje',
    getParentRoute: () => AuthPodesavanjaAirtableRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/setup': typeof SetupRoute
  '/istorija': typeof AuthIstorijaRoute
  '/monitoring': typeof AuthMonitoringRoute
  '/podesavanja': typeof AuthPodesavanjaRouteWithChildren
  '/shop-floor': typeof AuthShopFloorRoute
  '/api/manifest.webmanifest': typeof ApiManifestDotwebmanifestRoute
  '/podesavanja/airtable': typeof AuthPodesavanjaAirtableRouteWithChildren
  '/podesavanja/korisnici': typeof AuthPodesavanjaKorisniciRoute
  '/podesavanja/pwa': typeof AuthPodesavanjaPwaRoute
  '/podesavanja/role': typeof AuthPodesavanjaRoleRoute
  '/api/public/version': typeof ApiPublicVersionRoute
  '/podesavanja/': typeof AuthPodesavanjaIndexRoute
  '/podesavanja/airtable/mapiranje': typeof AuthPodesavanjaAirtableMapiranjeRoute
  '/api/public/airtable-webhook/monitoring': typeof ApiPublicAirtableWebhookMonitoringRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/setup': typeof SetupRoute
  '/istorija': typeof AuthIstorijaRoute
  '/monitoring': typeof AuthMonitoringRoute
  '/shop-floor': typeof AuthShopFloorRoute
  '/api/manifest.webmanifest': typeof ApiManifestDotwebmanifestRoute
  '/podesavanja/airtable': typeof AuthPodesavanjaAirtableRouteWithChildren
  '/podesavanja/korisnici': typeof AuthPodesavanjaKorisniciRoute
  '/podesavanja/pwa': typeof AuthPodesavanjaPwaRoute
  '/podesavanja/role': typeof AuthPodesavanjaRoleRoute
  '/api/public/version': typeof ApiPublicVersionRoute
  '/podesavanja': typeof AuthPodesavanjaIndexRoute
  '/podesavanja/airtable/mapiranje': typeof AuthPodesavanjaAirtableMapiranjeRoute
  '/api/public/airtable-webhook/monitoring': typeof ApiPublicAirtableWebhookMonitoringRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/setup': typeof SetupRoute
  '/_auth/istorija': typeof AuthIstorijaRoute
  '/_auth/monitoring': typeof AuthMonitoringRoute
  '/_auth/podesavanja': typeof AuthPodesavanjaRouteWithChildren
  '/_auth/shop-floor': typeof AuthShopFloorRoute
  '/api/manifest.webmanifest': typeof ApiManifestDotwebmanifestRoute
  '/_auth/podesavanja/airtable': typeof AuthPodesavanjaAirtableRouteWithChildren
  '/_auth/podesavanja/korisnici': typeof AuthPodesavanjaKorisniciRoute
  '/_auth/podesavanja/pwa': typeof AuthPodesavanjaPwaRoute
  '/_auth/podesavanja/role': typeof AuthPodesavanjaRoleRoute
  '/api/public/version': typeof ApiPublicVersionRoute
  '/_auth/podesavanja/': typeof AuthPodesavanjaIndexRoute
  '/_auth/podesavanja/airtable/mapiranje': typeof AuthPodesavanjaAirtableMapiranjeRoute
  '/api/public/airtable-webhook/monitoring': typeof ApiPublicAirtableWebhookMonitoringRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/setup'
    | '/istorija'
    | '/monitoring'
    | '/podesavanja'
    | '/shop-floor'
    | '/api/manifest.webmanifest'
    | '/podesavanja/airtable'
    | '/podesavanja/korisnici'
    | '/podesavanja/pwa'
    | '/podesavanja/role'
    | '/api/public/version'
    | '/podesavanja/'
    | '/podesavanja/airtable/mapiranje'
    | '/api/public/airtable-webhook/monitoring'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/setup'
    | '/istorija'
    | '/monitoring'
    | '/shop-floor'
    | '/api/manifest.webmanifest'
    | '/podesavanja/airtable'
    | '/podesavanja/korisnici'
    | '/podesavanja/pwa'
    | '/podesavanja/role'
    | '/api/public/version'
    | '/podesavanja'
    | '/podesavanja/airtable/mapiranje'
    | '/api/public/airtable-webhook/monitoring'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/setup'
    | '/_auth/istorija'
    | '/_auth/monitoring'
    | '/_auth/podesavanja'
    | '/_auth/shop-floor'
    | '/api/manifest.webmanifest'
    | '/_auth/podesavanja/airtable'
    | '/_auth/podesavanja/korisnici'
    | '/_auth/podesavanja/pwa'
    | '/_auth/podesavanja/role'
    | '/api/public/version'
    | '/_auth/podesavanja/'
    | '/_auth/podesavanja/airtable/mapiranje'
    | '/api/public/airtable-webhook/monitoring'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  SetupRoute: typeof SetupRoute
  ApiManifestDotwebmanifestRoute: typeof ApiManifestDotwebmanifestRoute
  ApiPublicVersionRoute: typeof ApiPublicVersionRoute
  ApiPublicAirtableWebhookMonitoringRoute: typeof ApiPublicAirtableWebhookMonitoringRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/manifest.webmanifest': {
      id: '/api/manifest.webmanifest'
      path: '/api/manifest.webmanifest'
      fullPath: '/api/manifest.webmanifest'
      preLoaderRoute: typeof ApiManifestDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/shop-floor': {
      id: '/_auth/shop-floor'
      path: '/shop-floor'
      fullPath: '/shop-floor'
      preLoaderRoute: typeof AuthShopFloorRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/podesavanja': {
      id: '/_auth/podesavanja'
      path: '/podesavanja'
      fullPath: '/podesavanja'
      preLoaderRoute: typeof AuthPodesavanjaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/monitoring': {
      id: '/_auth/monitoring'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof AuthMonitoringRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/istorija': {
      id: '/_auth/istorija'
      path: '/istorija'
      fullPath: '/istorija'
      preLoaderRoute: typeof AuthIstorijaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/podesavanja/': {
      id: '/_auth/podesavanja/'
      path: '/'
      fullPath: '/podesavanja/'
      preLoaderRoute: typeof AuthPodesavanjaIndexRouteImport
      parentRoute: typeof AuthPodesavanjaRoute
    }
    '/api/public/version': {
      id: '/api/public/version'
      path: '/api/public/version'
      fullPath: '/api/public/version'
      preLoaderRoute: typeof ApiPublicVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/podesavanja/role': {
      id: '/_auth/podesavanja/role'
      path: '/role'
      fullPath: '/podesavanja/role'
      preLoaderRoute: typeof AuthPodesavanjaRoleRouteImport
      parentRoute: typeof AuthPodesavanjaRoute
    }
    '/_auth/podesavanja/pwa': {
      id: '/_auth/podesavanja/pwa'
      path: '/pwa'
      fullPath: '/podesavanja/pwa'
      preLoaderRoute: typeof AuthPodesavanjaPwaRouteImport
      parentRoute: typeof AuthPodesavanjaRoute
    }
    '/_auth/podesavanja/korisnici': {
      id: '/_auth/podesavanja/korisnici'
      path: '/korisnici'
      fullPath: '/podesavanja/korisnici'
      preLoaderRoute: typeof AuthPodesavanjaKorisniciRouteImport
      parentRoute: typeof AuthPodesavanjaRoute
    }
    '/_auth/podesavanja/airtable': {
      id: '/_auth/podesavanja/airtable'
      path: '/airtable'
      fullPath: '/podesavanja/airtable'
      preLoaderRoute: typeof AuthPodesavanjaAirtableRouteImport
      parentRoute: typeof AuthPodesavanjaRoute
    }
    '/api/public/airtable-webhook/monitoring': {
      id: '/api/public/airtable-webhook/monitoring'
      path: '/api/public/airtable-webhook/monitoring'
      fullPath: '/api/public/airtable-webhook/monitoring'
      preLoaderRoute: typeof ApiPublicAirtableWebhookMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/podesavanja/airtable/mapiranje': {
      id: '/_auth/podesavanja/airtable/mapiranje'
      path: '/mapiranje'
      fullPath: '/podesavanja/airtable/mapiranje'
      preLoaderRoute: typeof AuthPodesavanjaAirtableMapiranjeRouteImport
      parentRoute: typeof AuthPodesavanjaAirtableRoute
    }
  }
}

interface AuthPodesavanjaAirtableRouteChildren {
  AuthPodesavanjaAirtableMapiranjeRoute: typeof AuthPodesavanjaAirtableMapiranjeRoute
}

const AuthPodesavanjaAirtableRouteChildren: AuthPodesavanjaAirtableRouteChildren =
  {
    AuthPodesavanjaAirtableMapiranjeRoute:
      AuthPodesavanjaAirtableMapiranjeRoute,
  }

const AuthPodesavanjaAirtableRouteWithChildren =
  AuthPodesavanjaAirtableRoute._addFileChildren(
    AuthPodesavanjaAirtableRouteChildren,
  )

interface AuthPodesavanjaRouteChildren {
  AuthPodesavanjaAirtableRoute: typeof AuthPodesavanjaAirtableRouteWithChildren
  AuthPodesavanjaKorisniciRoute: typeof AuthPodesavanjaKorisniciRoute
  AuthPodesavanjaPwaRoute: typeof AuthPodesavanjaPwaRoute
  AuthPodesavanjaRoleRoute: typeof AuthPodesavanjaRoleRoute
  AuthPodesavanjaIndexRoute: typeof AuthPodesavanjaIndexRoute
}

const AuthPodesavanjaRouteChildren: AuthPodesavanjaRouteChildren = {
  AuthPodesavanjaAirtableRoute: AuthPodesavanjaAirtableRouteWithChildren,
  AuthPodesavanjaKorisniciRoute: AuthPodesavanjaKorisniciRoute,
  AuthPodesavanjaPwaRoute: AuthPodesavanjaPwaRoute,
  AuthPodesavanjaRoleRoute: AuthPodesavanjaRoleRoute,
  AuthPodesavanjaIndexRoute: AuthPodesavanjaIndexRoute,
}

const AuthPodesavanjaRouteWithChildren = AuthPodesavanjaRoute._addFileChildren(
  AuthPodesavanjaRouteChildren,
)

interface AuthRouteChildren {
  AuthIstorijaRoute: typeof AuthIstorijaRoute
  AuthMonitoringRoute: typeof AuthMonitoringRoute
  AuthPodesavanjaRoute: typeof AuthPodesavanjaRouteWithChildren
  AuthShopFloorRoute: typeof AuthShopFloorRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthIstorijaRoute: AuthIstorijaRoute,
  AuthMonitoringRoute: AuthMonitoringRoute,
  AuthPodesavanjaRoute: AuthPodesavanjaRouteWithChildren,
  AuthShopFloorRoute: AuthShopFloorRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  SetupRoute: SetupRoute,
  ApiManifestDotwebmanifestRoute: ApiManifestDotwebmanifestRoute,
  ApiPublicVersionRoute: ApiPublicVersionRoute,
  ApiPublicAirtableWebhookMonitoringRoute:
    ApiPublicAirtableWebhookMonitoringRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
