// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'

// PERF: Supabase JS klijent se učitava LENJO i samo ako u localStorage
// postoji Supabase auth sesija (ključ oblika "sb-*-auth-token"). Ova
// aplikacija koristi PIN sesije (X-PIN-Session zaglavlje), pa Supabase
// sesija u browseru tipično ne postoji — middleware tada ne radi ništa i
// Supabase klijent se uopšte ne preuzima u početnom bundle-u (~25-30 KB gzip
// manje, i jedan async korak manje uz svaki serverFn poziv).
function hasSupabaseAuthSession(): boolean {
  try {
    for (let i = 0; i < localStorage.length; i++) {
      const k = localStorage.key(i)
      if (k && k.startsWith('sb-') && k.endsWith('-auth-token')) return true
    }
  } catch {
    /* noop */
  }
  return false
}

// Must be registered as a global `functionMiddleware` in `src/start.ts`; otherwise
// the browser never attaches the bearer token to serverFn RPCs.
export const attachSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    if (typeof window === 'undefined' || !hasSupabaseAuthSession()) return next()
    const { supabase } = await import('./client')
    const { data } = await supabase.auth.getSession()
    const token = data.session?.access_token
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  },
)
